# 실행하려는 컨테이너들 정의
services:
  order-service-blue:
    image: enterfive/order-service:v1
    ports:
      - "18082:8082"
    networks:
      my-network:
  order-service-green:
    image: enterfive/order-service:v2
    ports:
      - "28082:8082"
    networks:
      my-network:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
#      - ./nginx-blue.conf:/etc/nginx/nginx.conf
#      - ./nginx-green.conf:/etc/nginx/nginx.conf
#      - ./nginx-weight.conf:/etc/nginx/nginx.conf
      - ./nginx-abtest.conf:/etc/nginx/nginx.conf

    depends_on:
      - order-service-blue
      - order-service-green
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: ecommerce-network
